#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# emacsclient -e "(kill-emacs)"
# Check if a monitor is connected
if xrandr -q | grep -w "connected" | grep -v "eDP" >/dev/null; then
	# Monitor is present
	xrandr --output HDMI-A-0 --auto --right-of eDP --mode 1920x1080
	bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10 21
	bspc monitor HDMI-A-0 -d 11 12 13 14 15 16 17 18 19 20
else
	# Move all windows from workspaces 11-20 to their respective 1-10 workspaces
	#for i in {1..10}; do
	#   bspc node "@$((i+10)):/.*" --to-desktop $i
	#done

	# Remove extra desktops
	#for i in {11..20}; do
	#    bspc desktop $i -r
	# done

	bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21

	# Monitor is not present
	xrandr --output HDMI-A-0 --off
fi

bspc config border_width 1
bspc config normal_border_color "#a1a1a1"
bspc config active_border_color "#d1d1d1"
bspc config focused_border_color "#d1d1d1"

bspc config window_gap 0
bspc config top_padding 40
bspc config left_padding 10
bspc config right_padding 10
bspc config bottom_padding 10

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled

$HOME/.config/bspwm/start.sh
